// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.23.4
// source: proto/tencent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRoleLoginURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SecretId  string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretKey string `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Token     string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	SUrl      string `protobuf:"bytes,4,opt,name=s_url,json=sUrl,proto3" json:"s_url,omitempty"`
}

func (x *GenerateRoleLoginURLRequest) Reset() {
	*x = GenerateRoleLoginURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tencent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRoleLoginURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRoleLoginURLRequest) ProtoMessage() {}

func (x *GenerateRoleLoginURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tencent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRoleLoginURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateRoleLoginURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_tencent_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRoleLoginURLRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *GenerateRoleLoginURLRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *GenerateRoleLoginURLRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateRoleLoginURLRequest) GetSUrl() string {
	if x != nil {
		return x.SUrl
	}
	return ""
}

type GenerateRoleLoginURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GenerateRoleLoginURLResponse) Reset() {
	*x = GenerateRoleLoginURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tencent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRoleLoginURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRoleLoginURLResponse) ProtoMessage() {}

func (x *GenerateRoleLoginURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tencent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRoleLoginURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateRoleLoginURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_tencent_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRoleLoginURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_tencent_proto protoreflect.FileDescriptor

var file_proto_tencent_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a,
	0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x13,
	0x0a, 0x05, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x55, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x73, 0x0a, 0x0e, 0x54, 0x65, 0x6e, 0x63, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x12,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x67, 0x2d, 0x34, 0x69, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tencent_proto_rawDescOnce sync.Once
	file_proto_tencent_proto_rawDescData = file_proto_tencent_proto_rawDesc
)

func file_proto_tencent_proto_rawDescGZIP() []byte {
	file_proto_tencent_proto_rawDescOnce.Do(func() {
		file_proto_tencent_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tencent_proto_rawDescData)
	})
	return file_proto_tencent_proto_rawDescData
}

var file_proto_tencent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tencent_proto_goTypes = []interface{}{
	(*GenerateRoleLoginURLRequest)(nil),  // 0: proto.GenerateRoleLoginURLRequest
	(*GenerateRoleLoginURLResponse)(nil), // 1: proto.GenerateRoleLoginURLResponse
}
var file_proto_tencent_proto_depIdxs = []int32{
	0, // 0: proto.TencentService.GenerateRoleLoginURL:input_type -> proto.GenerateRoleLoginURLRequest
	1, // 1: proto.TencentService.GenerateRoleLoginURL:output_type -> proto.GenerateRoleLoginURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tencent_proto_init() }
func file_proto_tencent_proto_init() {
	if File_proto_tencent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tencent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRoleLoginURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tencent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRoleLoginURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tencent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tencent_proto_goTypes,
		DependencyIndexes: file_proto_tencent_proto_depIdxs,
		MessageInfos:      file_proto_tencent_proto_msgTypes,
	}.Build()
	File_proto_tencent_proto = out.File
	file_proto_tencent_proto_rawDesc = nil
	file_proto_tencent_proto_goTypes = nil
	file_proto_tencent_proto_depIdxs = nil
}
