// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: proto/tencent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TencentServiceClient is the client API for TencentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TencentServiceClient interface {
	GenerateRoleLoginURL(ctx context.Context, in *GenerateRoleLoginURLRequest, opts ...grpc.CallOption) (*GenerateRoleLoginURLResponse, error)
}

type tencentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTencentServiceClient(cc grpc.ClientConnInterface) TencentServiceClient {
	return &tencentServiceClient{cc}
}

func (c *tencentServiceClient) GenerateRoleLoginURL(ctx context.Context, in *GenerateRoleLoginURLRequest, opts ...grpc.CallOption) (*GenerateRoleLoginURLResponse, error) {
	out := new(GenerateRoleLoginURLResponse)
	err := c.cc.Invoke(ctx, "/proto.TencentService/GenerateRoleLoginURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TencentServiceServer is the server API for TencentService service.
// All implementations must embed UnimplementedTencentServiceServer
// for forward compatibility
type TencentServiceServer interface {
	GenerateRoleLoginURL(context.Context, *GenerateRoleLoginURLRequest) (*GenerateRoleLoginURLResponse, error)
	mustEmbedUnimplementedTencentServiceServer()
}

// UnimplementedTencentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTencentServiceServer struct {
}

func (UnimplementedTencentServiceServer) GenerateRoleLoginURL(context.Context, *GenerateRoleLoginURLRequest) (*GenerateRoleLoginURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRoleLoginURL not implemented")
}
func (UnimplementedTencentServiceServer) mustEmbedUnimplementedTencentServiceServer() {}

// UnsafeTencentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TencentServiceServer will
// result in compilation errors.
type UnsafeTencentServiceServer interface {
	mustEmbedUnimplementedTencentServiceServer()
}

func RegisterTencentServiceServer(s grpc.ServiceRegistrar, srv TencentServiceServer) {
	s.RegisterService(&TencentService_ServiceDesc, srv)
}

func _TencentService_GenerateRoleLoginURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRoleLoginURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TencentServiceServer).GenerateRoleLoginURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TencentService/GenerateRoleLoginURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TencentServiceServer).GenerateRoleLoginURL(ctx, req.(*GenerateRoleLoginURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TencentService_ServiceDesc is the grpc.ServiceDesc for TencentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TencentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TencentService",
	HandlerType: (*TencentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRoleLoginURL",
			Handler:    _TencentService_GenerateRoleLoginURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tencent.proto",
}
